-- =====================================================================
-- ATTENDANCE SUPABASE — SEED DATA
-- ---------------------------------------------------------------------
-- Run this AFTER schema.sql to populate demo employees, locations,
-- settings, and 7 days of attendance records.
--
-- Demo credentials:
--   EMP001 / EMP001123
--   EMP002 / EMP002123
--   ...
--   EMP008 / EMP008123
-- =====================================================================

-- ---- Locations ---------------------------------------------------------
insert into attendance_locations (name, latitude, longitude, allowed_radius, status)
values
  ('VGG Infra Office', 17.3850, 78.4867, 200, 'ACTIVE'),
  ('Site Office - Kokapet', 17.4126, 78.4028, 300, 'ACTIVE')
on conflict (name) do nothing;

-- ---- Employees ---------------------------------------------------------
-- Password hashes are SHA-256(salt:password). These match the hashes
-- generated by the Node `crypto`-based hashPassword() in employees.ts.
-- For demo purposes we use a known salt; the app's hashPassword() uses
-- a random salt per password. To regenerate, use the admin dashboard's
-- "Add Employee" or "Reset Password" feature after seeding.

insert into attendance_employees (id, employee_code, name, phone, department, role, status, password_hash)
values
  ('e0000001-0000-0000-0000-000000000001', 'EMP001', 'Ravi Kumar',      '9876543210', 'Construction', 'Site Engineer', 'ACTIVE', 'demo'),
  ('e0000001-0000-0000-0000-000000000002', 'EMP002', 'Priya Sharma',    '9876543211', 'HR',           'HR Manager',    'ACTIVE', 'demo'),
  ('e0000001-0000-0000-0000-000000000003', 'EMP003', 'Arjun Reddy',     '9876543212', 'Finance',      'Accountant',    'ACTIVE', 'demo'),
  ('e0000001-0000-0000-0000-000000000004', 'EMP004', 'Sneha Patel',     '9876543213', 'Construction', 'Supervisor',    'ACTIVE', 'demo'),
  ('e0000001-0000-0000-0000-000000000005', 'EMP005', 'Mohammed Iqbal',  '9876543214', 'Operations',   'Site Lead',     'ACTIVE', 'demo'),
  ('e0000001-0000-0000-0000-000000000006', 'EMP006', 'Lakshmi Nair',    '9876543215', 'Design',       'Architect',     'ACTIVE', 'demo'),
  ('e0000001-0000-0000-0000-000000000007', 'EMP007', 'Vikram Singh',    '9876543216', 'Operations',   'Operator',      'ACTIVE', 'demo'),
  ('e0000001-0000-0000-0000-000000000008', 'EMP008', 'Ananya Das',      '9876543217', 'HR',           'Recruiter',     'ACTIVE', 'demo')
on conflict (employee_code) do nothing;

-- ⚠️ NOTE: The password_hash above is 'demo' (placeholder).
-- After running this seed, use the admin dashboard to reset each
-- employee's password to <code>123 (e.g. EMP001 → EMP001123):
--   Dashboard → Staff Attendance → Employees → [employee] → Reset Password
-- Or run the Node seed script: bun run scripts/seed-attendance-supabase.ts

-- ---- Today's attendance (sample) --------------------------------------
-- Creates check-in records for today for 7 of the 8 employees.
-- Run this on the day you want to demo; adjust times as needed.

insert into attendance_records (employee_id, attendance_date, check_in_time, check_out_time, working_minutes, status, marked_by, check_in_location_id, check_in_distance)
select
  e.id,
  current_date,
  (current_date::timestamp + interval '9 hours' + (random() * interval '30 minutes')),
  (current_date::timestamp + interval '17 hours' + (random() * interval '30 minutes')),
  480,
  case
    when random() < 0.7 then 'PRESENT'
    when random() < 0.9 then 'LATE'
    else 'HALF_DAY'
  end,
  'staff',
  (select id::text from attendance_locations where name = 'VGG Infra Office' limit 1),
  floor(random() * 50)::int
from attendance_employees e
where e.employee_code in ('EMP001', 'EMP002', 'EMP003', 'EMP004', 'EMP005', 'EMP006', 'EMP007')
on conflict (employee_id, attendance_date) do nothing;

-- =====================================================================
-- DONE — now reset passwords via the admin dashboard or Node seed script.
-- =====================================================================
